config/routes.rb
Rails.application.routes.draw do
  resources :pocos
  get "home/index"
  root to: "home#index"
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create' 
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/poco.rb
class Poco < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :username, presence: true, 
                         uniqueness: {case_sensitive: false}, 
                         length: {minimum:3, maximum:25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                      uniqueness: {case_sensitive: false}, 
                      length: {maximum:100},
                      format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "Você deve estar logado para realizar essa ação!"
            redirect_to login_path
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/map_controller.rb
class MapController < ApplicationController
end

app/controllers/pocos_controller.rb
class PocosController < ApplicationController
  before_action :set_poco, only: %i[ show edit update destroy ]

  # GET /pocos or /pocos.json
  def index
    @pocos = Poco.all
  end

  # GET /pocos/1 or /pocos/1.json
  def show
    @poco = Poco.find(params[:id])
    gon.lat = @poco.lat
    gon.long = @poco.long
    gon.res = @poco.res
  end

  # GET /pocos/new
  def new
    @poco = Poco.new
  end

  # GET /pocos/1/edit
  def edit
  end

  # POST /pocos or /pocos.json
  def create
    @poco = Poco.new(poco_params)

    respond_to do |format|
      if @poco.save
        format.html { redirect_to poco_url(@poco), notice: "Poço adicionado com sucesso!" }
        format.json { render :show, status: :created, location: @poco }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @poco.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pocos/1 or /pocos/1.json
  def update
    respond_to do |format|
      if @poco.update(poco_params)
        format.html { redirect_to poco_url(@poco), notice: "Poço atualizado com sucesso!" }
        format.json { render :show, status: :ok, location: @poco }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @poco.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pocos/1 or /pocos/1.json
  def destroy
    @poco.destroy

    respond_to do |format|
      format.html { redirect_to pocos_url, notice: "Poço removido com sucesso!", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poco
      @poco = Poco.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def poco_params
      params.require(:poco).permit(:endereco, :complemento, :cidade, :estado, :telefone, :lat, :long, :res)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Log in realizado com sucesso!"
            redirect_to pocos_path
        else
            flash.now[:alert] = "Erro no log in!"
            render 'new', status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Log Out realizado com sucesso!"
        redirect_to root_path, status: :see_other
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
        if current_user != @user && !current_user.admin?
            # flash[:alert] = "Você só pode editar ou deletar seus próprios artigos"
            redirect_to @user, alert: "Você só pode editar ou deletar sua própria conta!"
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/pocos_helper.rb
module PocosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<main>

  <!-- style="background-image: linear-gradient(white, white, white, #9dc2d1);" -->
  <section class="text-center container">
    <div class="row pt-5 mb-5 d-flex justify-content-center align-items-center">
      <div class="col">
        <%= image_tag("AMA2.png", width: "350", :class => "pb-3") %>
        <%# <img src="./imgs/AMA2.png" style="width: 350px;" class="pb-3"> %>
      </div>
      <!-- d-flex justify-content-center align-items-center -->
      <div class="col text-center">
        <h1 class="fw-normal">Análise Microbiológica da Água</h1>
        <p class="lead text-muted">Verifique aqui a avaliação da qualidade microbiológica das águas utilizadas para o consumo humano pela população de Macau-RN.</p>
        <p>
          <%= link_to "Visualizar poços", pocos_path, class:"btn btn-outline-secondary btn-lg" %>
          <!-- <a class="btn btn-outline-secondary btn-lg" data-bs-toggle="collapse" data-bs-target="#mapa" role="button" aria-expanded="false" aria-controls="mapa">Visualizar poços</a> %> -->
          <!-- <a class="btn btn-outline-secondary btn-lg" data-bs-toggle="collapse" data-bs-target="#poco" role="button" aria-expanded="false" aria-controls="poco">Pesquisar poços</a> -->
        </p>
      </div>

      <!-- Mapa -->
      <div class="container collapse pb-3" id="mapa">
        <div class="card card-body">
          <div class="row">
              <h1 class="fw-normal mb-3">Clique nas marcações do mapa para obter informações.</h1>
              <div class="row d-flex justify-content-center">
                  <div class="col">
                    <%= image_tag("pocos_s.png", width: "30") %>
                    <%# <img src="./imgs/pocos_s.png" alt="" width="30"> %>
                    <p class="lead px-1">Poços Saudáveis</p>
                  </div>   
                  <div class="col">
                    <%= image_tag("pocos_c.png", width: "30") %>
                    <%# <img src="./imgs/pocos_c.png" alt="" width="30"> %>
                    <p class="lead px-1">Poços Contaminados</p>
                  </div>   
              </div>
              
              <iframe class="w-100 pb-3" height="480" src="https://www.google.com/maps/d/u/0/embed?mid=1_GQO0GniVmeL36I-EFOU2oP6hg7D2PHh&ehbc=2E312F&z=13"></iframe>   

              <p>
                  <a class="btn btn-secondary btn-lg" data-bs-toggle="collapse" data-bs-target="#mapa" role="button" aria-expanded="false" aria-controls="mapa">Fechar mapa</a>
              </p>       
          </div>
        </div>
      </div>

      <!-- Poco -->
      <div class="container collapse pb-3" id="poco">
        <div class="card card-body">
          <p>Em desenvolvimento...</p>

          <p>
              <a class="btn btn-secondary btn-lg" data-bs-toggle="collapse" data-bs-target="#poco" role="button" aria-expanded="false" aria-controls="poco">Fechar pesquisa</a>
          </p>

        </div>
      </div>

    </div>

  </section>

  <!-- SOBRE O PROJETO -->
  <section style="background-color: #9dc2d1;">
    <div class="container marketing text-center">
      <br>
        <div class="row featurette justify-content-center mx-5 my-5 flex-wrap-reverse">
            <div class="col-md-8">
                <h2 class="featurette-heading">Sobre o projeto</h2>
                <p class="lead">A ausência de água de boa qualidade afeta as condições de vida e a saúde das comunidades. Sabe-se que grande parte dos problemas decorrentes da má gestão dos recursos hídricos podem ser minimizados por companhas de educação ambiental na comunidade com foco na formação de cidadãos críticos e por análises periódicas da qualidade microbiológica da água ofertada, enfatizando a importância do consumo de uma água livre de contaminantes, bem como, fortalecendo o papel socioambiental dos sujeitos frente a percepção das ações antrópicas que comprometem a qualidade dessas águas. Somado a esses papeis os gestores dos municípios por meio das diversas secretarias municipais também precisam estar cientes das suas obrigações na distribuição de uma água de boa qualidade.</p>
            </div>
            <div class="col align-items-center py-2">
                <%= image_tag("poco1.jpg", :class => "img-fluid rounded") %>
                <%# <img class="img-fluid rounded" src="./imgs/poco1.jpg"> %>
            </div>
        </div>

      <hr class="featurette-divider">

      <div class="row featurette mx-2 my-5">
        <div class="col text-center py-2">
            <%= image_tag("esgoto.png", :class => "img-fluid rounded") %>
            <%# <img class="img-fluid rounded" src="./imgs/esgoto.png"> %>
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">A água como veículo de transmissão de doenças</h2>
          <p class="lead">A má qualidade dos recursos hídricos está diretamente associada a ocorrência de doenças, uma vez que, além da água ser um veículo de transmissão de agentes patológicos como protozoários, helmintos, bactérias e vírus, pode ser fonte de contaminação por produtos químicos (GUEDES et al., 2017). Portanto, “o desenvolvimento dos recursos hídricos não pode se desassociar da conservação ambiental, já que na essência envolve a sustentabilidade do homem no meio natural” (TUNDISI, 2003).</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette mx-2 my-5 flex-wrap-reverse">
        <div class="col-md-7">
          <h2 class="featurette-heading">Sustentabilidade hídrica e análises microbiológicas</h2>
          <p class="lead">O uso racional da água é atitude fundamental para o seu melhor aproveitamento, principalmente, levando-se em consideração que a região Nordestina Brasileira apresenta índices pluviométricos irregulares e, consequentemente, períodos de escassez de água (BRAGA, et al. 2005 apud FREIRE et al, 2015).O planejamento da utilização racional da água de fontes naturais deve levar em consideração a qualidade da água na perspectiva da saúde, garantindo que os consumidores não sejam expostos a patógenos que causam doenças (SADEGHI et al., 2006). Ademais, “nas regiões tropicais, a contaminação da água dos mananciais tende a aumentar na estação chuvosa devido, principalmente, à água de escoamento superficial” (NAUMOVA, 2006). O baixo índice de chuvas também interfere na qualidade e a quantidade de água consumida pela população, por meio do aumento de nutrientes orgânicos nos mananciais, causando eventos de eutrofização dos corpos hídricos, tais cenários podem ser decisivos no surgimento de problemas de saúde (GRIGOLETTO et al., 2016).</p>
        </div>
        <div class="col text-center py-2">
            <%= image_tag("analise.png", :class => "img-fluid rounded") %>
            <%# <img class="img-fluid rounded" src="./imgs/analise.png"> %>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette mx-2 my-5">
        <div class="col text-center py-2">
            <%= image_tag("aula.jpg", :class => "img-fluid rounded") %>
            <%# <img class="img-fluid rounded" src="./imgs/aula.jpg"> %>
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">Educação como agente de transformador da qualidade hídrica</h2>
          <p class="lead">A conscientização da população que consome a água em seus domicílios e nas suas atividades diárias é de suma importância para geração de cidadãos participativos com envolvimento nas ações de preservação dos recursos hídricos, por meio do consumo consciente e da preservação do meio ambiente (TEIXEIRA; MOURA; COELHO, 2016). Além disso, a população instruída pode atuar como multiplicadores na divulgação de ações que diminuam o desperdício e a contaminação das fontes de água utilizadas para o abastecimento humano, enfatizando a importância do monitoramento da qualidade microbiológica da água, uma vez que, ela pode atuar como veículo de transmissão de doenças, comprometendo a qualidade de vida da população e onerando os sistemas de saúde dos municípios. Neste contexto, o cidadão comum também deve ser educado e orientado a cobrar dos principais responsáveis o devido cuidado com os recursos ambientais (PADILHA et al, 2019).</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="container marketing">
        <div class="row d-flex justify-content-center align-items-center">

          <div class="row">
            <h2 class="featurette-heading text-center pb-5">Equipe de servidores e alunos</h2>
          </div>

          <div class="col-lg-4  text-center pb-3">
            <%= image_tag("foto_paula.png", width: "200", :class => "img-thumbnail rounded") %>
            <%# <img src="./imgs/foto_paula.png" class="img-thumbnail rounded" alt="" style="width: 200px;"> %>
            <h5 class="pt-1">Paula Ivani</h5>
            <p>Prof. de Biologia - IFRN/MC</p>
          </div>  

          <div class="col-lg-4  text-center pb-3">
            <%= image_tag("foto_cinthia.jpeg", width: "200", :class => "img-thumbnail rounded") %>
            <%# <img src="./imgs/foto_cinthia.jpeg" class="img-thumbnail rounded" alt="" style="width: 200px;"> %>
            <h5 class="pt-1">Cinthia Telles</h5>
            <p>Prof. de Biologia - IFRN/MC</p>
          </div>  

          <div class="col-lg-4  text-center pb-3">
            <%= image_tag("foto1.jpg", width: "200", :class => "img-thumbnail rounded") %>
            <%# <img src="./imgs/foto1.jpg" class="img-thumbnail rounded" alt="" style="width: 200px;"> %>
            <h5 class="pt-1">Guilherme Leal</h5>
            <p>Prof. de Sistemas de Informação - IFRN/MC</p>
          </div> 

          <div class="col-lg-4  text-center pb-3">
            <%= image_tag("foto_martina.jpeg", width: "200", :class => "img-thumbnail rounded") %>
            <%# <img src="./imgs/foto_martina.jpeg" class="img-thumbnail rounded" alt="" style="width: 200px;"> %>
            <h5 class="pt-1">Martina Martins</h5>
            <p>Téc. em Laboratório - IFRN/MC</p>
          </div>  

          <div class="col-lg-4  text-center pb-3">
            <%= image_tag("foto_paula.png", width: "200", :class => "img-thumbnail rounded") %>
            <%# <img src="./imgs/foto1.jpg" class="img-thumbnail rounded" alt="" style="width: 200px;"> %>
            <h5 class="pt-1">Sara Lima</h5>
            <p>Téc. em Laboratório - IFRN/LAJ</p>
          </div>  

          <div class="col-lg-4  text-center pb-3">
            <%= image_tag("foto_anderson.jpeg", width: "200", :class => "img-thumbnail rounded") %>
            <%# <img src="./imgs/foto_anderson.jpeg" class="img-thumbnail rounded" alt="" style="width: 200px;"> %>
            <h5 class="pt-1">Anderson Alves</h5>
            <p>Aluno - Técnico em Química - IFRN/MC</p>
          </div> 

          <div class="col-lg-4  text-center pb-3">
            <%= image_tag("foto_jadna.jpeg", width: "200", :class => "img-thumbnail rounded") %>
            <%# <img src="./imgs/foto_jadna.jpeg" class="img-thumbnail rounded" alt="" style="width: 200px;"> %>
            <h5 class="pt-1">Jadna Caroline</h5>
            <p>Aluna - Licenciatura em Biologia - IFRN/MC</p>
          </div>  

          <div class="col-lg-4  text-center pb-3">
            <%= image_tag("foto_fabio.jpeg", width: "200", :class => "img-thumbnail rounded") %>
            <%# <img src="./imgs/foto_fabio.jpeg" class="img-thumbnail rounded" alt="" style="width: 200px;"> %>
            <h5 class="pt-1">Fábio Pereira</h5>
            <p>Aluno - Licenciatura em Biologia - IFRN/MC</p>
          </div>  

          <div class="col-lg-4  text-center pb-3">
            <%= image_tag("foto_kaio.jpeg", width: "200", :class => "img-thumbnail rounded") %>
            <%# <img src="./imgs/foto_kaio.jpeg" class="img-thumbnail rounded" alt="" style="width: 200px;"> %>
            <h5 class="pt-1">Kaio Araújo</h5>
            <p>Aluno - Licenciatura em Biologia - IFRN/MC</p>
          </div>  


        </div>
      </div>
    </section>

  </div>

</main>

app/views/layouts/_footer.html.erb
<footer class="px-5 py-5" style="background-color: #246084;">
  <div class="row d-flex justify-content-center align-items-center">
    
    <div class="col text-center pb-3">
        <%= image_tag("ifrn.png", width: "300", :class => "img-fluid rounded") %>
        <%# <img src="./imgs/ifrn.png" style="width: 300px;"> %>
    </div>

    <div class="col">
      <h5 class="fw-bold">Núcleo de Extensão e Prática Profissional</h5>  
      <p>
        Rua das Margaridas, 300, COHAB <br>
        CEP 59.500-000 <br>
        Macau-RN
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name, msg| %> 
        <% if name == "notice" %>
            <div class="alert alert-success alert-dismissible fade show fw-bolder" role="alert">
                <%= msg %> 
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                </button>
            </div>
        <% else %>
            <div class="alert alert-danger alert-dismissible fade show fw-bolder" role="alert">
                <%= msg %> 
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                </button>
            </div>
        <% end %>
          
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<header>

  <div class="collapse" id="navbarHeader" style="background-color: #368bb5;">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="font-weight-bold">Sobre</h4>
          <p class="text-white"><em>Projeto desenvolvido como ação do Núcleo de Extensão e Prática e Profissional (NEPP) do IFRN - Campus Macau. Informações são disponibilizadas para a população de Macau acerca da importância da avaliação da qualidade dos corpos hídricos e do consumo consciente da água de abastecimento humano como medida de promoção a saúde.</em></p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="font-weight-bold">Contato</h4>
          <ul class="list-unstyled">
            <li>
                <%= image_tag("instagram.svg", size: "30x24", :class => "img-fluid d-inline-block align-text-top m-2") %>
                <%# <img src="./imgs/instagram.svg" alt="" width="30" height="24" class="d-inline-block align-text-top"> %>
                <a href="https://www.instagram.com/ama_pocossaudaveis_nepp.mc/" class="text-white">
                  Siga-nos no Instagram
                </a>
              </li>
            <li>
                <%= image_tag("email.svg", size: "30x24", :class => "img-fluid d-inline-block align-text-top m-2") %>
                <%# <img src="./imgs/email.svg" alt="" width="30" height="24" class="d-inline-block align-text-top"> %>
                <a href="mailto:ama.pocossaudaveis@ifrn.edu.br" class="text-white">
                  Enviar e-mail
                </a>
            </li>
            <li>
                <%= image_tag("admin.svg", size: "30x24", :class => "img-fluid d-inline-block align-text-top m-2") %>
                <%# <img src="./imgs/admin.svg" alt="" width="30" height="24" class="d-inline-block align-text-top"> %>
                <%# <a href="#" class="text-white">Login</a> %>
                <%= link_to "Login", login_path, class:"text-white" %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark shadow-sm" style="background-color: #246084;">
    <div class="container">
      
      <%= link_to "AMA - Poços Saudáveis", root_path, class:"navbar-brand d-flex align-items-center fw-bold" %>


      <% if logged_in? %>
        <div class="col align-items-center justify-content-center fw-bold">
          <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle fw-bold text-black" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <%= image_tag("admin.svg", size: "30x24", :class => "") %>
                    [<%= current_user.username %>]
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "Sair", logout_path, class: "nav-link", data: {turbo_confirm: "Quer fazer log out?", turbo_method: :delete} %>
                </ul>
          </li>    


        </div>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <title>AMA - Poços Saudáveis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= include_gon %>
  </head>

  <body class="d-flex flex-column">    
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pocos/_form.html.erb
<div class="container">
  <div class="row justify-content-md-center">

    <%= form_with(model: poco) do |form| %>
      
      <% if poco.errors.any? %>
        <div style="color: red">
          <ul>
            <% poco.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group my-2">
        <%= form.label "Endereço:", style: "display: block" %>
        <%= form.text_field :endereco, class: "form-control" %>
      </div>

      <div class="form-group my-2">
        <%= form.label "Complemento:", style: "display: block" %>
        <%= form.text_field :complemento, class: "form-control" %>
      </div>

      <div class="form-group my-2">
        <%= form.label "Cidade:", style: "display: block" %>
        <%= form.text_field :cidade, class: "form-control" %>
      </div>

      <div class="form-group my-2">
        <%= form.label "Estado:", style: "display: block" %>
        <%= form.text_field :estado, class: "form-control" %>
      </div>

      <div class="form-group my-2">
        <%= form.label "Telefone:", style: "display: block" %>
        <%= form.text_field :telefone, class: "form-control" %>
      </div>

      <div class="form-group my-2">
        <%= form.label "Latitude:", style: "display: block" %>
        <%= form.text_field :lat, class: "form-control" %>
      </div>

      <div class="form-group my-2">
        <%= form.label "Longitude:", style: "display: block" %>
        <%= form.text_field :long, class: "form-control" %>
      </div>

      <div class="form-group my-2">
        <%= form.label "Resultado:", style: "display: inline", class: "me-2" %>
        <%# <%= form.check_box :res, class: "form-check" %>
        <%= form.radio_button :res, true, checked: !!@poco.res %>
        <%= form.label :res, "Própria", value: "true", class: "me-2 fw-bold" %>
        <%= form.radio_button :res, false %>
        <%= form.label :res, "Imprópria", value: "false", class: "me-2 fw-bold" %>
      </div>

      <div class="col text-center my-4">
        <% if logged_in? %>
          <%= form.submit "Cadastrar", class:"btn btn-success my-4"%>
        <% end %>
        <%= link_to "Voltar", pocos_path, class:"btn btn-secondary px-4" %>
      </div>
    <% end %>

  </div>
</div>

app/views/pocos/_poco.html.erb
<h2 class="text-center my-4">Poço <%= poco.id %></h2>

<div class="container">
  <div class="row justify-content-center align-items-center">    
    <div class="col text-center">
      <a href="https://maps.google.com/?q=<%= poco.lat %>,<%= poco.long %>"><div class="container mb-4" data-controller="map" data-target="map.placeholder" style="height: 400px; width: 400px;"></div></a>
    </div>

    <div id="<%= dom_id poco %>" class="col text-center">
      <p>
        <strong>Endereco:</strong>
        <%= poco.endereco %>
      </p>

      <p>
        <strong>Complemento:</strong>
        <%= poco.complemento %>
      </p>

      <p>
        <strong>Cidade:</strong>
        <%= poco.cidade %>
      </p>

      <p>
        <strong>Estado:</strong>
        <%= poco.estado %>
      </p>

      <p>
        <strong>Telefone:</strong>
        <%= poco.telefone %>
      </p>

      <p>
        <strong>Lat:</strong>
        <%= poco.lat %>
      </p>

      <p>
        <strong>Long:</strong>
        <%= poco.long %>
      </p>

      <strong>Resultado:     
      <% if (poco.res) %>
        <p style="color: green">Própria</p>
      <% else %>
        <p style="color: red">Imprópria</p>
      <% end %>
      </strong>   
    </div>
  </div>
</div>

app/views/pocos/edit.html.erb
<h2 class="text-center my-4">Editar Poço <%= @poco.id %></h2>

<%= render "form", poco: @poco %>

<br>

app/views/pocos/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">

    <h1 class="text-center my-4 fw-bold">Lista de Poços</h1>

    <div>
      <table class="table table-hover text-center">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Endereço</th>
            <th scope="col">Complemento</th>
            <th scope="col">Cidade</th>
            <th scope="col">Estado</th>
            <th scope="col">Telefone</th>
            <th scope="col">Latitude</th>
            <th scope="col">Longitude</th>
            <th scope="col">Resultado</th>
            <th scope="col"></th>
          </tr>
        </thead>

        <tbody>
          <% @pocos.each do |poco| %>  
            <tr>            
              <td><%= poco.id %></th>
              <td><%= poco.endereco %></td>
              <td><%= poco.complemento %></td>
              <td><%= poco.cidade %></td>
              <td><%= poco.estado %></td>
              <td><%= poco.telefone %></td>
              <td><%= poco.lat %></td>
              <td><%= poco.long %></td>
              <td>
                <% if(poco.res) %>
                  <p class="res-p fw-bold">Própria</p>
                <% else %>  
                  <p class="res-imp fw-bold">Imprópria</p>
                <% end %>
              </td>
              <td>
                <%= link_to "Exibir", poco, class:"btn btn-outline-secondary" %>
                <% if logged_in? %>
                  <%= link_to "Editar", edit_poco_path(poco), class:"btn btn-primary" %>
                  <%= link_to "Excluir", poco_path(poco), class:"btn btn-danger", data: {turbo_confirm: "Tem certeza?", turbo_method: :delete} %>
                <% end %>
              </td>
            </tr>
          <% end %>
          
        </tbody>

      </table>
    </div>

    <% if logged_in? %>
      <div class="col-4 text-center">
        <%= link_to "Novo poço", new_poco_path, class:"btn btn-success my-4" %>
      </div>
    <% end %>

  </div>
</div>

app/views/pocos/new.html.erb
<div class="container">
  <div class="row justify-content-md-center">

    <h2 class="text-center my-4">Cadastrar Novo Poço</h2>

      <%= render "form", poco: @poco %>

      <br>

  </div>
</div>

app/views/pocos/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">

    <%= render @poco %>

    <div class="col text-center my-4">
      <% if logged_in? %>
        <%= link_to "Editar", edit_poco_path(@poco), class:"btn btn-primary" %>
        <%= link_to "Excluir", poco_path(@poco), class:"btn btn-danger", data: {turbo_confirm: "Tem certeza?", turbo_method: :delete} %>
      <% end %>
      <%= link_to "Voltar", pocos_path, class:"btn btn-secondary" %>
    </div>

  </div>
</div>